name    'andyshinn-scribble'
version '0.0.1'
source 'https://github.com/andyshinn/puppet-scribble.git'
author 'andyshinn'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'https://github.com/andyshinn/puppet-scribble'
dependency 'puppetlabs/concat', '>= 1.0.0'
dependency 'puppetlabs/concat', '>= 4.1.0'
